### ISSUE TITLE
Separate App For User Profile, How Do We Tie This To Questions App?

### ISSUE THREAD

**Issue by chadzilla2080** [pymike00/The-Complete-Guide-To-DRF-and-VueJS#1]
In looking at your source code it seems like we would have been able to maybe use this with Question app, however, you set this up as a brand, brand new project. How can we tie the author to the user profile model? Can we just import and extend it?

**Comment by pymike00** [comment]
I am closing here as we have already discussed the issue on Udemy.

Happy Coding!
